input_data_path: "../data/heart.csv"
output_model_path: "../models/model.pkl"
metric_path: "../models/metrics.json"
splitting_params:
  val_size: 0.1
  random_state: 42
train_params:
  model_type: "LogisticRegression"
  model_param:
    solver: 'saga'
    penalty: 'l1'
    max_iter: 1000
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  sq_features:
    - "age"
  target_col: "target"
metric_params:
  metric_name: "roc_auc_score"
