apiVersion: v1
kind: Pod
metadata:
    name: online-inference
    labels:
        app: online-inference
spec:
    containers:
        -   image: panda1987ds/online_inference:v0.1
            resources:
                requests:
                    memory: "64Mi"
                    cpu: "250m"
                limits:
                    memory: "128Mi"
                    cpu: "500m"
            name: online-inference
            ports:
                -   containerPort: 8080
